### ISSUE TITLE
Failing to connect to MQTT - no state printed to log

### ISSUE THREAD

**Issue by pjv** [HeimdallMidgard/ESP-32-BLE-Scanner#1]
Hi,

I’m trying this out and with everything set up per your instructions, the esp32 device seems to be scanning successfully and seeing the beacon configured in the HA mobile app on my Android phone. I can see it logging the UUID and Distance every few seconds.

But it is not writing anything to my MQTT server. In the esp32 device logs it says
````
Connecting to MQTT...
failed with state
````

looking at your code it seems that `client.state()` is an empty string.

My MQTT server is nothing special, it’s on the same LAN as the esp32 device, allows anonymous connections (my setup leaves MQTT user and MQTT password (which by the way is mislabeled “wifi password”) blank. Other MQTT clients on the same LAN are able to connect to it with the same IP address and port configured. The MQTT logs the attempted connection from the esp32 device but then immediately logs:
`Socket error on client <unknown>, disconnecting.`

Any ideas?

**Comment by pjv** [comment]
It seems to be an authentication issue. I put my Home Assistant credentials into the setup page for MQTT and now it says it is connected to MQTT.

But... it does not seem to be creating the configured state topic `ESP32 BLE Scanner/Scan` on the MQTT server and therefore, the HA sensor entity is not being updated.

**Comment by HeimdallMidgard** [comment]
Yeah you are right. There is a bug when you enter no mqtt user and pw and also the webui is saying Wifi PW. I will fix this in the next version. 
Can you please check your mqtt server if the esp is connected correctly? You are getting scan results over serial connection and webui right?

**Comment by pjv** [comment]
Yes, I am seeing the scan results over the serial connection and webui.

I’m not sure how to check if the esp is connected correctly with mqtt. In the mqtt log it shows this:
`New client connected from 10.111.5.102 as mqtt-explorer-3c8480e1 (p2, c1, k60).`

...which seems ok.

But using an MQTT explorer tool to look at the topics on the broker, I can see that that there is no `ESP32 BLE Scanner/Scan` topic being created.

My main HA config has this:

````
sensor:
    - platform: mqtt_room
    device_id: '44f1d7eb-747e-4833-8a73-53744415c3be'
    name: 'Office Presence'
    state_topic: "ESP32 BLE Scanner/Scan"
    timeout: 60
    away_timeout: 30
````
And this is being processed by HA because it is creating the entity `sensor.office_presence`

Should the `state_topic` be created when HA starts? Or does it not get created until your code on the ESP device publishes?

**Comment by HeimdallMidgard** [comment]
I guess your HA Setup is wrong. It should be sth like this: 

```
sensor:
  - platform: mqtt_room
    device_id: '44f1d7eb-747e-4833-8a73-53744415c3be'
    name: 'Name of your mobile device or person e.g _pjv_ ' 
    state_topic: "ESP32 BLE Scanner/Scan"
    timeout: 60
    away_timeout: 30
```

The topic where the device will publish scans to will be "ESP32 BLE Scanner/Scan/**Your room and hostname**". So the Sensor name will needs to be your personal or mobile device name "_pjv_". The status of the sensor will than change according to the room where your mobile device will be scanned (If you are having several. Else it will only show no result or the roomname). So your **Your room and hostname** need to be e.g. office and the sensor in home assistant will track your name/mobile device over several rooms. You don't have to create a sensor in home assistant for your room. You create it for a person or mobile device. 

But just in case there is really nothing published can you check if there are more topics below "ESP32 BLE Scanner/Scan" and tell me your hostname/roomname.

**Comment by pjv** [comment]
Thank you for the clarifications.

In the web UI for the scanner, in the field for Room, I have “office”.

I have changed the HA setup as follows:

````
sensor:
  - platform: mqtt_room
    device_id: '44f1d7eb-747e-4833-8a73-53744415c3be'
    name: 'pjvA71'
    state_topic: "ESP32 BLE Scanner/Scan"
    timeout: 60
    away_timeout: 30
````

In the `name` key I have put the same string as the device name from the device management page. I hope I am now understanding that correctly.

However, I think whatever mistakes I may be making in the HA setup are secondary to the issue that as far as I can tell the scanner is not successfully publishing to my MQTT broker at all. I have an mqtt explorer tool connected to my broker listening to all topics (“#”) and there is no "ESP32 BLE Scanner/Scan" on my broker at all. Not just nothing underneath that; the top level ”ESP32 BLE Scanner" does not exist on my broker at all.

In your code here:

https://github.com/HeimdallMidgard/ESP-32-BLE-Scanner/blob/5090b3c7492093c840942a5f2cfe2e7c97dce5bc/src/main.cpp#L240

... does that `client.publish` call not return anything that might be useful for debugging?
